title = "Logo"
baseURL = "https://babylonbyte.com"
defaultContentLanguage = "en"
languageCode = "en"
hasCJKLanguage = false
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

theme = "FixIt"

[module]
  [[module.imports]]
    path = "github.com/hugo-fixit/FixIt"
